version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=ecom
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres    
    ports:
      - "5432:5432"